export type MaterialCategorySuggestionGroup = {
  section: string
  items: string[]
}

export const MATERIAL_CATEGORY_SUGGESTIONS: MaterialCategorySuggestionGroup[] = [
  {
    section: 'Electrical',
    items: [
      'Cable',
      'Containment',
      'Tray',
      'Trunking',
      'Conduit',
      'Accessories',
      'Switchgear',
      'Distribution Boards',
      'Consumer Units',
      'Earthing',
      'Fixings',
      'Sundries',
    ],
  },
  {
    section: 'Mechanical',
    items: [
      'Pipework',
      'Valves & Fittings',
      'Pumps',
      'Heating',
      'Cooling',
      'Ventilation',
      'Ductwork',
      'Insulation',
      'Controls',
      'Plant',
      'Sundries',
    ],
  },
  {
    section: 'Plumbing',
    items: [
      'Pipework',
      'Fittings',
      'Valves',
      'Sanitaryware',
      'Taps & Mixers',
      'Showers',
      'Drainage',
      'Water Heaters',
      'Tanks',
      'Pumps',
      'Sundries',
    ],
  },
  {
    section: 'Building Materials',
    items: [
      'Timber',
      'Sheet Materials',
      'Bricks & Blocks',
      'Cement & Concrete',
      'Plasterboard',
      'Plaster & Render',
      'Insulation',
      'Roofing',
      'Cladding',
      'Sealants & Adhesives',
      'Fixings',
    ],
  },
  {
    section: 'Finishes',
    items: [
      'Flooring',
      'Tiles',
      'Paint & Decorating',
      'Ceilings',
      'Wall Finishes',
      'Joinery',
      'Doors',
      'Ironmongery',
      'Kitchens',
    ],
  },
  {
    section: 'Fire & Security',
    items: [
      'Fire Alarm',
      'Fire Stopping',
      'Sprinklers',
      'Fire Protection',
      'CCTV',
      'Access Control',
      'Intruder Alarm',
      'Security',
    ],
  },
  {
    section: 'Technology & Controls',
    items: ['BMS', 'Controls', 'Data', 'Networking', 'AV', 'Communications'],
  },
  {
    section: 'Site',
    items: [
      'PPE',
      'Tools',
      'Plant',
      'Access Equipment',
      'Temporary Works',
      'Site Consumables',
      'Waste',
      'Signage',
      'External Works',
      'Groundworks',
      'Drainage',
      'Civils',
      'Landscaping',
      'Paving',
      'Fencing',
      'External Lighting',
    ],
  },
  {
    section: 'Specialist',
    items: [
      'Specialist Equipment',
      'Lifts',
      'Kitchen Equipment',
      'Commercial Catering',
      'Renewable Energy',
      'Solar PV',
      'EV Charging',
    ],
  },
  {
    section: 'Other',
    items: ['Other'],
  },
]
