import { format } from 'date-fns'
import type { TimesheetSubject } from '@/lib/timesheets/timesheetWeekUtils'
import { formatCurrency } from '@/lib/weekly-report/weeklyReportPayroll'

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function buildTimesheetInvoiceHtml({
  organizationName,
  subject,
  weekStart,
  weekEnd,
  totalHours,
  totalDays,
  amount,
  vatNumber,
  utrNumber,
}: {
  organizationName: string
  subject: TimesheetSubject
  weekStart: Date
  weekEnd: Date
  totalHours: number
  totalDays: number
  amount: number | null
  vatNumber?: string
  utrNumber?: string
}): string {
  const invoiceDate = format(new Date(), 'd MMMM yyyy')
  const period = `${format(weekStart, 'd MMM')} – ${format(weekEnd, 'd MMM yyyy')}`
  const invoiceRef = `INV-${subject.name.replace(/\s+/g, '').slice(0, 8).toUpperCase()}-${format(weekStart, 'yyyyMMdd')}`

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Invoice — ${escapeHtml(subject.name)}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #111827;
      margin: 36px;
      font-size: 12px;
      line-height: 1.45;
    }
    .brand { font-size: 10px; font-weight: 700; letter-spacing: 0.18em; color: #64748b; }
    h1 { font-size: 20px; margin: 8px 0 4px; letter-spacing: 0.06em; }
    .muted { color: #64748b; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 20px 0; }
    .box { border: 1px solid #dbe3ee; border-radius: 8px; padding: 12px; background: #f8fafc; }
    .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 18px; }
    th, td { border: 1px solid #dbe3ee; padding: 10px 8px; text-align: left; }
    th { background: #f8fafc; font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; }
    .total { font-size: 16px; font-weight: 700; margin-top: 18px; }
    .footer { margin-top: 24px; font-size: 10px; color: #64748b; }
  </style>
</head>
<body>
  <div class="brand">PROJECTPLANNER</div>
  <h1>TIMESHEET INVOICE</h1>
  <p class="muted">${escapeHtml(organizationName)}</p>

  <div class="grid">
    <div class="box">
      <div class="label">Contractor</div>
      <div><strong>${escapeHtml(subject.name)}</strong></div>
      <div class="muted">${escapeHtml(subject.kind === 'manager' ? 'Manager / admin' : 'Operative')}</div>
    </div>
    <div class="box">
      <div class="label">Invoice details</div>
      <div><strong>Reference:</strong> ${escapeHtml(invoiceRef)}</div>
      <div><strong>Invoice date:</strong> ${escapeHtml(invoiceDate)}</div>
      <div><strong>Period:</strong> ${escapeHtml(period)}</div>
    </div>
  </div>

  ${vatNumber ? `<p><strong>VAT number:</strong> ${escapeHtml(vatNumber)}</p>` : ''}
  ${utrNumber ? `<p><strong>UTR:</strong> ${escapeHtml(utrNumber)}</p>` : ''}

  <table>
    <thead>
      <tr><th>Description</th><th>Hours</th><th>Days</th><th>Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>Labour — week of ${format(weekStart, 'd MMM yyyy')}</td>
        <td>${totalHours.toFixed(1)}</td>
        <td>${totalDays.toFixed(2)}</td>
        <td>${amount != null ? formatCurrency(amount) : '—'}</td>
      </tr>
    </tbody>
  </table>

  <p class="total">Total due: ${amount != null ? formatCurrency(amount) : 'Rate not set'}</p>
  <div class="footer">Generated by Project Planner · ${escapeHtml(invoiceRef)}</div>
</body>
</html>`
}

export function downloadTimesheetInvoice(html: string, filename: string): void {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

export function printTimesheetInvoice(html: string): void {
  const printWindow = window.open('', '_blank', 'noopener,noreferrer,width=900,height=700')
  if (!printWindow) {
    downloadTimesheetInvoice(html, 'timesheet-invoice.html')
    return
  }
  printWindow.document.open()
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  printWindow.onload = () => printWindow.print()
}
