/**
 * Blank toolbox talk in the same sections as the PDF.
 * Excel opens this SpreadsheetML file. Fill the pale cells, save, print, then upload it.
 */

const SS = 'urn:schemas-microsoft-com:office:spreadsheet'
const X = 'urn:schemas-microsoft-com:office:excel'

export type BlankTalkFields = {
  title: string
  category: string
  trades: string
  project: string
  weekCommencing: string
  presentedBy: string
  purpose: string
  keyPoints: string[]
}

function escapeXml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function unescapeXml(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&')
}

function styledCell(value: string, style: string, mergeAcross = 0): string {
  const merge = mergeAcross > 0 ? ` ss:MergeAcross="${mergeAcross}"` : ''
  return `<Cell ss:StyleID="${style}"${merge}><Data ss:Type="String">${escapeXml(value)}</Data></Cell>`
}

function row(cells: string[], height?: number): string {
  const h = height ? ` ss:Height="${height}"` : ''
  return `<Row${h}>${cells.join('')}</Row>`
}

export function blankTalkWorkbookXml(): string {
  const rows = [
    row(
      [
        styledCell('PROJECT PLANNER', 'brand', 2),
        styledCell('TOOLBOX TALK', 'brandMuted', 1),
        styledCell('REF', 'brandMuted'),
        styledCell('TBT-BLANK', 'brandRef'),
      ],
      28
    ),
    row([styledCell('', 'amber', 6)], 6),
    row([styledCell('TITLE', 'label', 1), styledCell('', 'input', 4)], 22),
    row(
      [
        styledCell('CATEGORY', 'label'),
        styledCell('General', 'input'),
        styledCell('TRADES', 'label'),
        styledCell('', 'input', 1),
        styledCell('VERSION', 'label'),
        styledCell('1', 'input'),
      ],
      22
    ),
    row(
      [
        styledCell('PROJECT', 'label'),
        styledCell('', 'input', 1),
        styledCell('WEEK COMMENCING', 'label'),
        styledCell('', 'input'),
        styledCell('PRESENTED BY', 'label'),
        styledCell('', 'input'),
      ],
      22
    ),
    row([styledCell('PURPOSE', 'section', 6)], 20),
    row([styledCell('', 'inputTall', 6)], 36),
    row([styledCell('', 'inputTall', 6)], 36),
    row([styledCell('KEY CONTROL POINTS', 'section', 6)], 20),
    row([styledCell('Key point 1', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('Key point 2', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('Key point 3', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('Key point 4', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('Key point 5', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('Key point 6', 'pointLabel', 1), styledCell('', 'input', 4)], 22),
    row([styledCell('REFERENCES', 'section', 6)], 20),
    row(
      [styledCell('Master RAMS  ·  Relevant legislation  ·  Permit to Work (where applicable)', 'note', 6)],
      24
    ),
    row([styledCell('ATTENDEE SIGN-OFF', 'section', 6)], 20),
    row(
      [
        styledCell('NAME', 'tableHead', 1),
        styledCell('TRADE', 'tableHead'),
        styledCell('SIGNATURE', 'tableHead', 1),
        styledCell('DATE & TIME', 'tableHead', 1),
      ],
      20
    ),
    ...Array.from({ length: 8 }, () =>
      row(
        [
          styledCell('', 'sign', 1),
          styledCell('', 'sign'),
          styledCell('', 'sign', 1),
          styledCell('', 'sign', 1),
        ],
        24
      )
    ),
    row([styledCell('Generated by Project Planner  ·  TBT-BLANK  ·  v1', 'footer', 6)], 18),
  ]

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="${SS}" xmlns:ss="${SS}" xmlns:x="${X}">
  <Styles>
    <Style ss:ID="brand"><Font ss:Bold="1" ss:Size="16" ss:Color="#FFFFFF"/><Interior ss:Color="#0E1F33" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="brandMuted"><Font ss:Bold="1" ss:Size="12" ss:Color="#9EB2CE"/><Interior ss:Color="#0E1F33" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="brandRef"><Font ss:Bold="1" ss:Size="14" ss:Color="#FFFFFF"/><Interior ss:Color="#0E1F33" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="amber"><Interior ss:Color="#E69F29" ss:Pattern="Solid"/></Style>
    <Style ss:ID="label"><Font ss:Bold="1" ss:Size="10" ss:Color="#9AA6B4"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="section"><Font ss:Bold="1" ss:Size="12" ss:Color="#2BBBED"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="input"><Font ss:Size="12" ss:Color="#16263B"/><Interior ss:Color="#F6F9FC" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/></Borders><Alignment ss:Vertical="Center" ss:WrapText="1"/></Style>
    <Style ss:ID="inputTall"><Font ss:Size="12" ss:Color="#16263B"/><Interior ss:Color="#F6F9FC" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/></Borders><Alignment ss:Vertical="Top" ss:WrapText="1"/></Style>
    <Style ss:ID="pointLabel"><Font ss:Bold="1" ss:Size="11" ss:Color="#2F3E50"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="note"><Font ss:Size="11" ss:Color="#5B6B80"/><Interior ss:Color="#F6F9FC" ss:Pattern="Solid"/><Alignment ss:Vertical="Center" ss:WrapText="1"/></Style>
    <Style ss:ID="tableHead"><Font ss:Bold="1" ss:Size="10" ss:Color="#FFFFFF"/><Interior ss:Color="#0E1F33" ss:Pattern="Solid"/><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="sign"><Font ss:Size="11" ss:Color="#16263B"/><Interior ss:Color="#FFFFFF" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/><Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E6EEF5"/></Borders><Alignment ss:Vertical="Center"/></Style>
    <Style ss:ID="footer"><Font ss:Size="9" ss:Color="#9AA6B4"/><Alignment ss:Vertical="Center"/></Style>
  </Styles>
  <Worksheet ss:Name="Toolbox talk">
    <Table>
      <Column ss:Width="120"/>
      <Column ss:Width="140"/>
      <Column ss:Width="150"/>
      <Column ss:Width="140"/>
      <Column ss:Width="120"/>
      <Column ss:Width="80"/>
      <Column ss:Width="120"/>
      ${rows.join('\n      ')}
    </Table>
    <WorksheetOptions xmlns="${X}">
      <PageSetup>
        <Layout x:Orientation="Portrait"/>
        <PageMargins x:Bottom="0.5" x:Left="0.4" x:Right="0.4" x:Top="0.5"/>
      </PageSetup>
      <FitToPage/>
      <Print>
        <FitWidth>1</FitWidth>
        <FitHeight>1</FitHeight>
        <PaperSizeIndex>9</PaperSizeIndex>
      </Print>
    </WorksheetOptions>
  </Worksheet>
</Workbook>`
}

export function spreadsheetRowsFromXml(xml: string): string[][] {
  const rows: string[][] = []
  const rowMatches = xml.match(/<Row\b[^>]*>[\s\S]*?<\/Row>/g) || []
  for (const block of rowMatches) {
    const cells = [...block.matchAll(/<Data\b[^>]*>([\s\S]*?)<\/Data>/g)].map((match) =>
      unescapeXml(match[1].replace(/\s+/g, ' ').trim())
    )
    rows.push(cells)
  }
  return rows
}

function label(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, ' ')
}

export function parseBlankTalkRows(rows: string[][]): BlankTalkFields | null {
  const fields: BlankTalkFields = {
    title: '',
    category: '',
    trades: '',
    project: '',
    weekCommencing: '',
    presentedBy: '',
    purpose: '',
    keyPoints: [],
  }
  let purposeNext = false
  const purposeLines: string[] = []
  for (const cells of rows) {
    const a = label(cells[0] || '')
    const b = (cells[1] || '').trim()
    if (a === 'title') {
      fields.title = b
      purposeNext = false
      continue
    }
    if (a === 'category') {
      fields.category = b
      const tradesIndex = cells.findIndex((cell) => label(cell) === 'trades')
      if (tradesIndex >= 0) fields.trades = (cells[tradesIndex + 1] || '').trim()
      continue
    }
    if (a === 'project') {
      fields.project = b
      const weekIndex = cells.findIndex((cell) => label(cell) === 'week commencing')
      if (weekIndex >= 0) fields.weekCommencing = (cells[weekIndex + 1] || '').trim()
      const presentedIndex = cells.findIndex((cell) => label(cell) === 'presented by')
      if (presentedIndex >= 0) fields.presentedBy = (cells[presentedIndex + 1] || '').trim()
      continue
    }
    if (a === 'purpose') {
      purposeNext = true
      if (b) purposeLines.push(b)
      continue
    }
    if (a === 'key control points' || a === 'references' || a === 'attendee sign-off' || a === 'name') {
      purposeNext = false
    }
    if (purposeNext && (cells[0] || '').trim() && a !== 'key control points') {
      purposeLines.push((cells[0] || '').trim())
    }
    if (a.startsWith('key point')) {
      const point = b || (cells[2] || '').trim()
      if (point) fields.keyPoints.push(point)
    }
  }
  fields.purpose = purposeLines.join('\n').trim()
  const recognised = Boolean(fields.title || fields.purpose || fields.keyPoints.length || fields.category)
  return recognised ? fields : null
}

export function parseBlankTalkWorkbookXml(xml: string): BlankTalkFields | null {
  if (!xml.includes('<Workbook')) return null
  return parseBlankTalkRows(spreadsheetRowsFromXml(xml))
}

export async function readBlankTalkFile(file: File): Promise<BlankTalkFields | null> {
  const name = file.name.toLowerCase()
  const buffer = await file.arrayBuffer()
  const asText = new TextDecoder().decode(buffer)
  if (asText.includes('<Workbook')) return parseBlankTalkWorkbookXml(asText)
  if (!name.endsWith('.xlsx') && !name.endsWith('.xls') && !asText.startsWith('PK')) return null
  const XLSX = await import('xlsx')
  const book = XLSX.read(buffer, { type: 'array' })
  const sheet = book.Sheets[book.SheetNames[0]]
  if (!sheet) return null
  const rows = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: false, defval: '' }) as string[][]
  return parseBlankTalkRows(rows.map((row) => row.map((cell) => String(cell ?? ''))))
}

export function downloadBlankTalkExcel(): void {
  const blob = new Blob([blankTalkWorkbookXml()], { type: 'application/vnd.ms-excel' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'toolbox-talk-blank.xls'
  document.body.appendChild(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1500)
}
