import { format } from 'date-fns'
import type { HSToolboxIssue, HSToolboxSignature, HSToolboxTalk, Project, User } from '@/types'

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function buildToolboxTalkPdfHtml({
  talk,
  issue,
  signatures,
  users,
  project,
  organizationName,
  presentedBy,
}: {
  talk: HSToolboxTalk
  issue: HSToolboxIssue
  signatures: HSToolboxSignature[]
  users: User[]
  project: Project
  organizationName: string
  presentedBy: string
}): string {
  const ref = talk.referenceCode || talk.id
  const signedCount = signatures.filter((sig) => sig.status === 'signed').length
  const attendeeRows = signatures.map((sig) => {
    const user = users.find((entry) => entry.id === sig.userId)
    const name = user ? `${user.firstName || ''} ${user.surname || ''}`.trim() || user.email : 'Operative'
    const trade = user?.tradeTypeCustom || user?.tradeTypePreset || talk.trades[0] || 'General'
    const signedAt = sig.signedAt ? format(sig.signedAt, "d MMM yyyy 'at' HH:mm") : ''
    const signatureCell = sig.signatureImageBase64
      ? `<img src="${sig.signatureImageBase64}" alt="Signature" style="max-height:36px;" />`
      : 'Awaiting'
    return `
      <tr>
        <td>${escapeHtml(name)}</td>
        <td>${escapeHtml(trade)}</td>
        <td>${signatureCell}</td>
        <td>${escapeHtml(signedAt)}</td>
      </tr>`
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Toolbox Talk — ${escapeHtml(talk.title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #111827; margin: 32px; font-size: 12px; }
    .brand { font-size: 10px; font-weight: 700; letter-spacing: 0.18em; color: #64748b; }
    .title { font-size: 18px; font-weight: 700; margin: 8px 0; }
    .ref { font-size: 11px; color: #64748b; margin-bottom: 16px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 16px 0; }
    .box { border: 1px solid #dbe3ee; border-radius: 8px; padding: 10px; background: #f8fafc; }
    .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; margin-bottom: 4px; }
    h3 { font-size: 12px; margin: 18px 0 8px; }
    ul { margin: 0; padding-left: 18px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #dbe3ee; padding: 8px; text-align: left; vertical-align: top; }
    th { background: #f8fafc; font-size: 10px; text-transform: uppercase; }
    .footer { margin-top: 20px; font-size: 10px; color: #64748b; }
  </style>
</head>
<body>
  <div class="brand">PROJECTPLANNER</div>
  <div class="title">TOOLBOX TALK</div>
  <div class="ref">REF ${escapeHtml(ref)}</div>
  <h2 style="margin:0 0 8px;font-size:16px;">${escapeHtml(talk.title)}</h2>
  <p style="margin:0;color:#475569;">${escapeHtml(ref)} · ${escapeHtml(talk.category)} · v${talk.version} · ${escapeHtml(talk.status)}</p>

  <div class="grid">
    <div class="box"><div class="label">Project</div><div>${escapeHtml(project.jobNumber)}</div></div>
    <div class="box"><div class="label">Week commencing</div><div>W/C ${format(issue.weekCommencing, 'd MMM yyyy')}</div></div>
    <div class="box"><div class="label">Presented by</div><div>${escapeHtml(presentedBy || organizationName)}</div></div>
    <div class="box"><div class="label">Organisation</div><div>${escapeHtml(organizationName)}</div></div>
  </div>

  <h3>Purpose</h3>
  <p>${escapeHtml(talk.purpose || '—')}</p>

  <h3>Key control points</h3>
  <ul>${(talk.keyPoints.length ? talk.keyPoints : ['—']).map((point) => `<li>${escapeHtml(point)}</li>`).join('')}</ul>

  <h3>References</h3>
  <p>Master RAMS · Relevant legislation · Permit to Work (where applicable)</p>

  <h3>Attendee sign-off</h3>
  <table>
    <thead><tr><th>Name</th><th>Trade</th><th>Signature</th><th>Date &amp; time</th></tr></thead>
    <tbody>${attendeeRows.join('')}</tbody>
  </table>
  <p>${signedCount} of ${signatures.length} operative${signatures.length === 1 ? '' : 's'} signed.</p>

  <div class="footer">Generated by Project Planner · ${escapeHtml(ref)} · v${talk.version}</div>
</body>
</html>`
}

export function openToolboxTalkPdf(html: string, filename: string): void {
  const printWindow = window.open('', '_blank', 'noopener,noreferrer,width=900,height=700')
  if (!printWindow) return
  printWindow.document.open()
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  printWindow.onload = () => printWindow.print()

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}
