/**
 * Organisation origin-country → IANA zone.
 * Phone/browser location is ignored. A GB org always uses Europe/London even
 * if the user is a calendar day ahead abroad. iOS still uses Calendar.current
 * (device zone) until that app is updated to match.
 *
 * Codes match BANK_HOLIDAY_REGIONS / org setup. Unlisted codes fall back to London.
 */
import { LONDON_TIME_ZONE } from '@/lib/orgTime/zoneTime'

const COUNTRY_TIME_ZONES: Record<string, string> = {
  GB: 'Europe/London',
  UK: 'Europe/London',
  'GB-ENG': 'Europe/London',
  'GB-SCT': 'Europe/London',
  'GB-NIR': 'Europe/London',
  IE: 'Europe/Dublin',
  IM: 'Europe/Isle_of_Man',
  JE: 'Europe/Jersey',
  GG: 'Europe/Guernsey',
  AD: 'Europe/Andorra',
  AL: 'Europe/Tirane',
  AM: 'Asia/Yerevan',
  AO: 'Africa/Luanda',
  AR: 'America/Argentina/Buenos_Aires',
  AT: 'Europe/Vienna',
  AU: 'Australia/Sydney',
  AW: 'America/Aruba',
  AX: 'Europe/Mariehamn',
  BA: 'Europe/Sarajevo',
  BB: 'America/Barbados',
  BD: 'Asia/Dhaka',
  BE: 'Europe/Brussels',
  BG: 'Europe/Sofia',
  BJ: 'Africa/Porto-Novo',
  BO: 'America/La_Paz',
  BR: 'America/Sao_Paulo',
  BS: 'America/Nassau',
  BW: 'Africa/Gaborone',
  BY: 'Europe/Minsk',
  BZ: 'America/Belize',
  CA: 'America/Toronto',
  CD: 'Africa/Kinshasa',
  CG: 'Africa/Brazzaville',
  CH: 'Europe/Zurich',
  CL: 'America/Santiago',
  CN: 'Asia/Shanghai',
  CO: 'America/Bogota',
  CR: 'America/Costa_Rica',
  CU: 'America/Havana',
  CY: 'Asia/Nicosia',
  CZ: 'Europe/Prague',
  DE: 'Europe/Berlin',
  DK: 'Europe/Copenhagen',
  DM: 'America/Dominica',
  DO: 'America/Santo_Domingo',
  EC: 'America/Guayaquil',
  EE: 'Europe/Tallinn',
  EG: 'Africa/Cairo',
  ES: 'Europe/Madrid',
  FI: 'Europe/Helsinki',
  FO: 'Atlantic/Faroe',
  FR: 'Europe/Paris',
  GA: 'Africa/Libreville',
  GD: 'America/Grenada',
  GE: 'Asia/Tbilisi',
  GH: 'Africa/Accra',
  GI: 'Europe/Gibraltar',
  GL: 'America/Nuuk',
  GM: 'Africa/Banjul',
  GP: 'America/Guadeloupe',
  GR: 'Europe/Athens',
  GT: 'America/Guatemala',
  GY: 'America/Guyana',
  HK: 'Asia/Hong_Kong',
  HN: 'America/Tegucigalpa',
  HR: 'Europe/Zagreb',
  HT: 'America/Port-au-Prince',
  HU: 'Europe/Budapest',
  ID: 'Asia/Jakarta',
  IN: 'Asia/Kolkata',
  IS: 'Atlantic/Reykjavik',
  IT: 'Europe/Rome',
  JM: 'America/Jamaica',
  JP: 'Asia/Tokyo',
  KE: 'Africa/Nairobi',
  KR: 'Asia/Seoul',
  KY: 'America/Cayman',
  KZ: 'Asia/Almaty',
  LC: 'America/St_Lucia',
  LI: 'Europe/Vaduz',
  LS: 'Africa/Maseru',
  LT: 'Europe/Vilnius',
  LU: 'Europe/Luxembourg',
  LV: 'Europe/Riga',
  MA: 'Africa/Casablanca',
  MC: 'Europe/Monaco',
  MD: 'Europe/Chisinau',
  ME: 'Europe/Podgorica',
  MG: 'Indian/Antananarivo',
  MK: 'Europe/Skopje',
  MN: 'Asia/Ulaanbaatar',
  MQ: 'America/Martinique',
  MS: 'America/Montserrat',
  MT: 'Europe/Malta',
  MX: 'America/Mexico_City',
  MZ: 'Africa/Maputo',
  NA: 'Africa/Windhoek',
  NE: 'Africa/Niamey',
  NG: 'Africa/Lagos',
  NI: 'America/Managua',
  NL: 'Europe/Amsterdam',
  NO: 'Europe/Oslo',
  NZ: 'Pacific/Auckland',
  PA: 'America/Panama',
  PE: 'America/Lima',
  PG: 'Pacific/Port_Moresby',
  PH: 'Asia/Manila',
  PL: 'Europe/Warsaw',
  PR: 'America/Puerto_Rico',
  PT: 'Europe/Lisbon',
  PY: 'America/Asuncion',
  RO: 'Europe/Bucharest',
  RS: 'Europe/Belgrade',
  RU: 'Europe/Moscow',
  SC: 'Indian/Mahe',
  SE: 'Europe/Stockholm',
  SG: 'Asia/Singapore',
  SI: 'Europe/Ljubljana',
  SJ: 'Arctic/Longyearbyen',
  SK: 'Europe/Bratislava',
  SM: 'Europe/San_Marino',
  SR: 'America/Paramaribo',
  SV: 'America/El_Salvador',
  TN: 'Africa/Tunis',
  TR: 'Europe/Istanbul',
  UA: 'Europe/Kyiv',
  UG: 'Africa/Kampala',
  US: 'America/New_York',
  UY: 'America/Montevideo',
  VA: 'Europe/Vatican',
  VE: 'America/Caracas',
  VN: 'Asia/Ho_Chi_Minh',
  ZA: 'Africa/Johannesburg',
  ZW: 'Africa/Harare',
}

export function ianaTimeZoneForCountry(countryCode?: string | null): string {
  const code = (countryCode || 'GB').trim().toUpperCase()
  return COUNTRY_TIME_ZONES[code] || LONDON_TIME_ZONE
}

export { LONDON_TIME_ZONE, COUNTRY_TIME_ZONES }
